version: "3.7"

services:
  thehive:
    image: strangebee/thehive:5.2
    restart: unless-stopped
    depends_on:
      - cassandra
      - elasticsearch
      - minio
      - cortex.local
    mem_limit: 1500m
    ports:
      - "${THEHIVE_PORT}:9000"
    environment:
      - JVM_OPTS="${THEHIVE_JVM_OPTS}"
    command:
      - --secret
      - "${THEHIVE_SECRET}"
      - "--cql-hostnames"
      - "${CASSANDRA_HOST}"
      - "--index-backend"
      - "elasticsearch"
      - "--es-hostnames"
      - "${ELASTICSEARCH_HOST}"
      - "--s3-endpoint"
      - "${MINIO_ENDPOINT}"
      - "--s3-access-key"
      - "${MINIO_ACCESS_KEY}"
      - "--s3-secret-key"
      - "${MINIO_SECRET_KEY}"
      - "--s3-use-path-access-style"
    volumes:
      - thehivedata:/etc/thehive/application.conf
    networks:
      - SOC_NET

  cassandra:
    image: 'cassandra:4'
    restart: unless-stopped
    ports:
      - "${CASSANDRA_PORT}:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=${CASSANDRA_CLUSTER_NAME}
    volumes:
      - cassandradata:/var/lib/cassandra
    networks:
      - SOC_NET
    
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    restart: unless-stopped
    mem_limit: 512m
    ports:
      - "${ELASTICSEARCH_PORT}:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - cluster.name=${ELASTICSEARCH_CLUSTER_NAME}
      - http.host=0.0.0.0
      - "ES_JAVA_OPTS=${ELASTICSEARCH_JAVA_OPTS}"
    volumes:
      - elasticsearchdata:/usr/share/elasticsearch/data
    networks:
      - SOC_NET

  minio:
    image: quay.io/minio/minio
    restart: unless-stopped
    command: ["minio", "server", "/data", "--console-address", ":9002"]
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    ports:
      - "${MINIO_PORT}:9002"
    volumes:
      - miniodata:/data
    networks:
      - SOC_NET

  cortex.local:
    image: thehiveproject/cortex:latest
    restart: unless-stopped
    environment:
      - job_directory=/tmp/cortex-jobs
      - docker_job_directory=/tmp/cortex-jobs
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/cortex-jobs:/tmp/cortex-jobs
      - ./cortex/logs:/var/log/cortex
      - ./cortex/application.conf:/cortex/application.conf
    depends_on:
      - elasticsearch
    ports:
      - "${CORTEX_PORT}:9001"
    networks:
      - SOC_NET

volumes:
  miniodata:
  cassandradata:
  elasticsearchdata:
  thehivedata:

networks:
  SOC_NET:
    driver: bridge